---
title: "Chi-Square With Ordinal Data"
author: "Wenjun He"
date: "`r format(Sys.Date(),'%d %B, %Y')`"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
---

参考材料

 - [Real Statistics support for nominal-ordinal chi-square test](https://www.real-statistics.com/one-way-analysis-of-variance-anova/nominal-ordinal-chi-square-test/real-statistics-support-for-nominal-ordinal-chi-square-test/)
 
 - [Chi-Square With Ordinal Data](https://www.uvm.edu/~statdhtx/StatPages/More_Stuff/OrdinalChisq/OrdinalChiSq.html)
 
 - [Association Tests for Ordinal Tables](https://rcompanion.org/handbook/H_09.html#:~:text=The%20linear-by-linear%20test%20can%20be%20used%20to%20test,performed%20by%20permutation%20test%20with%20the%20coin%20package.)

# Table 1
```{r ,echo=FALSE, warning=FALSE, message=FALSE}
library(coin)
Input =(
"ordinal <200 200-400 >400 
nominal
    1  61 9 24 
    2  64 11 20 
")
Tabla = as.table(read.ftable(textConnection(Input)))
Tabla
Test = chisq_test(Tabla,
                  scores = list("ordinal" = c(1, 2, 3)))
Test
```
# Table 2
```{r ,echo=FALSE, warning=FALSE, message=FALSE}
Input =(
"ordinal <10 10-19.9 >=20 
nominal
    1  72 18 4 
    2  74 17 4 
")
Tabla = as.table(read.ftable(textConnection(Input)))
Tabla
Test = chisq_test(Tabla,
                  scores = list("ordinal" = c(1, 2, 3)))
Test
```

# Table 3
```{r ,echo=FALSE, warning=FALSE, message=FALSE}
Input =(
"ordinal 1 2 3 
nominal
    1  62 21 11 
    2  67 18 10 
")
Tabla = as.table(read.ftable(textConnection(Input)))
Tabla
Test = chisq_test(Tabla,
                  scores = list("ordinal" = c(1, 2, 3)))
Test
```
# Table 4
```{r ,echo=FALSE, warning=FALSE, message=FALSE}
Input =(
"ordinal 1 2 3 
nominal
    1  49 20 11 
    2  38 31 18 
")
Tabla = as.table(read.ftable(textConnection(Input)))
Tabla
Test = chisq_test(Tabla,
                  scores = list("ordinal" = c(1, 2, 3)))
Test
```

# Table 5
```{r ,echo=FALSE, warning=FALSE, message=FALSE}
Input =(
"ordinal <200 200-400 >400 
nominal
    1  37 17 26 
    2  41 16 30 
")
Tabla = as.table(read.ftable(textConnection(Input)))
Tabla
Test = chisq_test(Tabla,
                  scores = list("ordinal" = c(1, 2, 3)))
Test
```